package constants

type AuthorizationContextKey string

var AUTHORIZATION_CONTEXT_KEY AuthorizationContextKey = "AUTHORIZATION_CONTEXT"

type RequestIdKey string

var REQUEST_ID_KEY RequestIdKey = "REQUEST_ID"

const (
	SqlNoRows = "sql: no rows in result set"
)

const (
	DEFAULT_API_PREFIX   = "/api"
	DEFAULT_API_PORT     = "80"
	DEFAULT_API_TLS_PORT = "443"
	CURRENT_USER_ENV_VAR = "PD_CURRENT_USER"
)

const (
	HMAC_SECRET_ENV_VAR     = "HMAC_SECRET"
	LOG_LEVEL_ENV_VAR       = "LOG_LEVEL"
	SECURITY_KEY_ENV_VAR    = "SECURITY_PRIVATE_KEY"
	TLS_ENABLED_ENV_VAR     = "TLS_ENABLED"
	TLS_PORT_ENV_VAR        = "TLS_PORT"
	TLS_CERTIFICATE_ENV_VAR = "TLS_CERTIFICATE"
	TLS_PRIVATE_KEY_ENV_VAR = "TLS_PRIVATE_KEY"
	TOKEN_DURATION_MINUTES  = 60
	API_PORT_ENV_VAR        = "API_PORT"
	API_PREFIX_ENV_VAR      = "API_PREFIX"
)

const (
	API_PORT_FLAG         = "port"
	UPDATE_ROOT_PASSWORD  = "update-root-pass"
	GENERATE_SECURITY_KEY = "gen-rsa"
	FILE_FLAG             = "file"
)

const (
	USER_ROLE       = "USER"
	SUPER_USER_ROLE = "SUPER_USER"
	READ_ONLY_CLAIM = "READ_ONLY"

	LIST_CLAIM   = "LIST"
	CREATE_CLAIM = "CREATE"
	DELETE_CLAIM = "DELETE"
	UPDATE_CLAIM = "UPDATE"

	LIST_USER   = "LIST_USER"
	CREATE_USER = "CREATE_USER"
	DELETE_USER = "DELETE_USER"
	UPDATE_USER = "UPDATE_USER"

	LIST_VM_CLAIM            = "LIST_VM"
	CREATE_VM_CLAIM          = "CREATE_VM"
	DELETE_VM_CLAIM          = "DELETE_VM"
	UPDATE_VM_STATES_CLAIM   = "UPDATE_VM_STATES"
	UPDATE_VM_CLAIM          = "UPDATE_VM"
	EXECUTE_COMMAND_VM_CLAIM = "EXECUTE_COMMAND_VM"

	LIST_PACKER_TEMPLATE_CLAIM   = "LIST_PACKER_TEMPLATE"
	CREATE_PACKER_TEMPLATE_CLAIM = "CREATE_PACKER_TEMPLATE"
	DELETE_PACKER_TEMPLATE_CLAIM = "DELETE_PACKER_TEMPLATE"
	UPDATE_PACKER_TEMPLATE_CLAIM = "UPDATE_PACKER_TEMPLATE"

	LIST_CATALOG_MANIFEST_CLAIM   = "LIST_CATALOG_MANIFEST"
	CREATE_CATALOG_MANIFEST_CLAIM = "CREATE_CATALOG_MANIFEST"
	DELETE_CATALOG_MANIFEST_CLAIM = "DELETE_CATALOG_MANIFEST"
	UPDATE_CATALOG_MANIFEST_CLAIM = "UPDATE_CATALOG_MANIFEST"
	PULL_CATALOG_MANIFEST_CLAIM   = "PULL_CATALOG_MANIFEST"
	PUSH_CATALOG_MANIFEST_CLAIM   = "PUSH_CATALOG_MANIFEST"
	IMPORT_CATALOG_MANIFEST_CLAIM = "IMPORT_CATALOG_MANIFEST"
)

var AllSystemRoles = []string{
	USER_ROLE,
	SUPER_USER_ROLE,
}

var AllSystemClaims = []string{
	READ_ONLY_CLAIM,
	CREATE_CLAIM,
	DELETE_CLAIM,
	UPDATE_CLAIM,
	LIST_CLAIM,
	LIST_USER,
	CREATE_USER,
	DELETE_USER,
	UPDATE_USER,
	CREATE_VM_CLAIM,
	DELETE_VM_CLAIM,
	LIST_VM_CLAIM,
	UPDATE_VM_STATES_CLAIM,
	UPDATE_VM_CLAIM,
	EXECUTE_COMMAND_VM_CLAIM,
	CREATE_PACKER_TEMPLATE_CLAIM,
	DELETE_PACKER_TEMPLATE_CLAIM,
	LIST_PACKER_TEMPLATE_CLAIM,
	UPDATE_PACKER_TEMPLATE_CLAIM,
	CREATE_CATALOG_MANIFEST_CLAIM,
	DELETE_CATALOG_MANIFEST_CLAIM,
	LIST_CATALOG_MANIFEST_CLAIM,
	UPDATE_CATALOG_MANIFEST_CLAIM,
	PULL_CATALOG_MANIFEST_CLAIM,
	PUSH_CATALOG_MANIFEST_CLAIM,
	IMPORT_CATALOG_MANIFEST_CLAIM,
}

var DefaultRoles = []string{
	USER_ROLE,
}

var DefaultClaims = []string{
	READ_ONLY_CLAIM,
	LIST_CATALOG_MANIFEST_CLAIM,
	LIST_PACKER_TEMPLATE_CLAIM,
	LIST_VM_CLAIM,
	LIST_CLAIM,
}
