---
#########################
#########################
## Golang Linter rules ##
#########################
#########################

# configure golangci-lint
# see https://github.com/golangci/golangci-lint/blob/master/.golangci.example.yml
issues:
  exclude-rules:
    - path: .*_test\.go
      linters:
        - dupl
        - gosec
        - goconst
linters:
  disable-all: true
  enable:
    - bodyclose
    - dogsled
    - errcheck
    - funlen
    - gocognit
    - goconst
    - gocritic
    - goimports
    - revive
    - goprintffuncname
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - staticcheck
    - nestif
    - typecheck
    - unconvert
    - unparam
    - whitespace
  fast: true
linters-settings:
  errcheck:
    check-type-assertions: true
  gocognit:
    min-complexity: 30
  goconst:
    min-len: 3
    min-occurrences: 3
  gocritic:
    enabled-checks:
      - appendCombine
      - badCall
      - badCond
      - boolExprSimplify
      - codegenComment
      - commentFormatting
      - commentedOutCode
      - deprecatedComment
      - dupImport
      - emptyFallthrough
      - emptyStringTest
      - equalFold
      - evalOrder
      - exitAfterDefer
      - flagName
      - hexLiteral
      - indexAlloc
      - initClause
      - methodExprCall
      - nestingReduce
      - newDeref
      - nilValReturn
      - offBy1
      - ptrToRefParam
      - rangeExprCopy
      - regexpPattern
      - sloppyReassign
      - stringXbytes
      - truncateCmp
      - typeAssertChain
      - typeUnparen
      - underef
      - unnecessaryBlock
      - valSwap
      - weakCond
      - wrapperFunc
      - yodaStyleExpr
  gocyclo:
    min-complexity: 10
  govet:
    check-shadowing: false
  nestif:
    min-complexity: 8
  revive:
    rules:
      - name: unused-parameter
        disabled: true
run:
  timeout: 5m
  issues-exit-code: 1
  concurrency: 8
  tests: true
  skip-dirs:
    - vendor
  skip-files:
    - .*_test\.go
    - src\api_documentation\example_processor\golang.go

output:
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true
  sort-results: true
  format: colored-line-number
