version: '3.9'
name: devops-service
services:
  devops:
    build: .
    ports:
      - 5570:80/tcp
      - 40000:40000/tcp
    security_opt:
      - 'apparmor:unconfined'
      - 'seccomp:unconfined'
    cap_add:
      - SYS_PTRACE
    env_file:
      - .env.all
