apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm.fullname" . }}
  namespace: {{ include "helm.namespace" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
data:
  LOG_LEVEL: {{ .Values.logLevel }}
  TLS_PORT: {{ .Values.ingress.tls.port | quote }}
  API_PORT: {{ .Values.ingress.apiPort | quote }}
  API_PREFIX: {{ .Values.ingress.apiPrefix }}
  DATABASE_FOLDER: {{ .Values.storage.databasePath }}
  {{- if .Values.config.mode }}
  MODE: {{ .Values.config.mode }}
  {{- else }}
  MODE: "api"
  {{- end }}
  JWT_DURATION: {{ .Values.security.jwt.duration | quote }}
  JWT_SIGN_ALGORITHM: {{ .Values.security.jwt.signing_method | quote }}
  SECURITY_PASSWORD_MIN_PASSWORD_LENGTH: {{ .Values.security.password.min_password_length | quote }}
  SECURITY_PASSWORD_MAX_PASSWORD_LENGTH: {{ .Values.security.password.max_password_length | quote }}
  SECURITY_PASSWORD_REQUIRE_LOWERCASE: {{ .Values.security.password.require_lowercase | quote }}
  SECURITY_PASSWORD_REQUIRE_UPPERCASE: {{ .Values.security.password.require_uppercase | quote }}
  SECURITY_PASSWORD_REQUIRE_NUMBER: {{ .Values.security.password.require_numbers | quote }}
  SECURITY_PASSWORD_REQUIRE_SPECIAL_CHAR: {{ .Values.security.password.require_special_characters | quote }}
  SECURITY_PASSWORD_SALT_PASSWORD: {{ .Values.security.password.salt_password | quote }}
  BRUTE_FORCE_MAX_LOGIN_ATTEMPTS: {{ .Values.security.brute_force.max_login_attempts | quote }}
  BRUTE_FORCE_LOCKOUT_DURATION: {{ .Values.security.brute_force.lockout_duration | quote }}
  BRUTE_FORCE_INCREMENTAL_WAIT: {{ .Values.security.brute_force.increment_lockout_duration | quote }}
  TLS_DISABLE_VALIDATION: {{ .Values.security.disable_tls_validation | quote }}
  SYSTEM_AUTO_RECOVER_DATABASE: {{ .Values.storage.autoRecover | quote }}