{{- if and .Values.storage.databasePath .Values.storage.node_name }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "helm.fullname" . }}
  namespace: {{ include "helm.namespace" . }}
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: manual
  local:
    path: /mnt/pd-devops-{{ include "helm.fullname" . }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ .Values.storage.node_name }}
{{- end }}

