apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm.fullname" . }}
  namespace: {{ include "helm.namespace" . }}
  labels: {{- include "helm.labels" . | nindent 4 }}
  annotations:
    sidecar.istio.io/proxyConfig: |
      proxyMetadata:
        ISTIO_META_HTTP_TIMEOUT: "86400s"  # 24h in seconds
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector: {{- include "helm.selectorLabels" . | nindent 4 }}
