package constants

const (
	BRUTE_FORCE_MAX_LOGIN_ATTEMPTS_ENV_VAR = "BRUTE_FORCE_MAX_LOGIN_ATTEMPTS"
	BRUTE_FORCE_LOCKOUT_DURATION_ENV_VAR   = "BRUTE_FORCE_LOCKOUT_DURATION"
	BRUTE_FORCE_INCREMENTAL_WAIT_ENV_VAR   = "BRUTE_FORCE_INCREMENTAL_WAIT"
)
