package constants

const (
	JWT_PRIVATE_KEY_ENV_VAR    = "JWT_PRIVATE_KEY"
	JWT_HMACS_SECRET_ENV_VAR   = "JWT_HMACS_SECRET"
	JWT_DURATION_ENV_VAR       = "JWT_DURATION"
	JWT_SIGN_ALGORITHM_ENV_VAR = "JWT_SIGN_ALGORITHM"
)
