package constants

const (
	SECURITY_PASSWORD_MIN_PASSWORD_LENGTH_ENV_VAR  = "SECURITY_PASSWORD_MIN_PASSWORD_LENGTH"
	SECURITY_PASSWORD_MAX_PASSWORD_LENGTH_ENV_VAR  = "SECURITY_PASSWORD_MAX_PASSWORD_LENGTH"
	SECURITY_PASSWORD_REQUIRE_LOWERCASE_ENV_VAR    = "SECURITY_PASSWORD_REQUIRE_LOWERCASE"
	SECURITY_PASSWORD_REQUIRE_UPPERCASE_ENV_VAR    = "SECURITY_PASSWORD_REQUIRE_UPPERCASE"
	SECURITY_PASSWORD_REQUIRE_NUMBER_ENV_VAR       = "SECURITY_PASSWORD_REQUIRE_NUMBER"
	SECURITY_PASSWORD_REQUIRE_SPECIAL_CHAR_ENV_VAR = "SECURITY_PASSWORD_REQUIRE_SPECIAL_CHAR"
	SECURITY_PASSWORD_SALT_PASSWORD_ENV_VAR        = "SECURITY_PASSWORD_SALT_PASSWORD"
)
