name: Feature Request
description: Suggest an idea for this project
title: "[FEATURE]"
labels:
  - triage
  - feature request
assignees:
  - cjlapao
body:
  - type: textarea
    id: feature_description
    attributes:
      label: Is your feature request related to a problem? Please describe.
      value: |-
        A clear and concise description of what the problem is. Ex. I'm always frustrated
        when [...]
    validations:
      required: true
  - type: textarea
    id: describe_feature
    attributes:
      label: Describe how would you expect the feature to work
      value: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: describe_alternatives
    attributes:
      label: Describe alternatives you've considered
      value: A clear and concise description of any alternative solutions or features you've considered.
  - type: textarea
    id: additional_context
    attributes:
      label: Additional context
      value: Add any other context or screenshots about the feature request here.
