name: Product Backlog Item
description: Create a product backlog item
title: "[PBI] "
labels:
  - triage
  - pbi
assignees:
  - cjlapao
projects:
  - "Parallels/6"
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: |-
        Provide a clear and concise description of the item. Explain the purpose and the expected outcome.
    validations:
      required: true
  - type: textarea
    id: user_story
    attributes:
      label: User Story
      placeholder: |-
        As a **[type of user]**, I want **[some goal]** so that **[some reason]**.
    validations:
      required: true
  - type: textarea
    id: describe_feature
    attributes:
      label: Acceptance Criteria
      placeholder: |-
        - [ ] **Criterion 1**: Detailed description of the first acceptance criterion.
      description: |
        Define the conditions that must be met for the item to be considered complete.
  - type: checkboxes
    id: definition_of_done
    attributes:
      label: Definition of Done
      options:
        - label: Code implemented following best practices.
        - label: Unit tests written and passing.
        - label: Code reviewed and approved.
        - label: Merged into the main branch.
        - label: Documentation updated (if applicable).
        - label: Deployed to staging/production environment.

  - type: textarea
    id: assumptions_and_constraints
    attributes:
      label: Assumptions and Constraints
      placeholder: |-
        - **Assumption 1**: Detailed description of the first assumption.
          - List any assumptions that are being made about the item.
        - **Constraint 1**: Detailed description of the first constraint.
          - List any constraints that may impact the implementation of the item.
  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies
      placeholder: |-
        - **Dependency 1**: Detailed description of the first dependency.
  - type: textarea
    id: additional_context
    attributes:
      label: Additional Notes
      placeholder: Add any other context or screenshots about the item here.
