#!/usr/bin/env bash

while getopts ":d:p:" opt; do
  case $opt in
  p)
    PACKAGE_NAME=$OPTARG
    ;;
  d)
    DIRECTORY=$OPTARG
    ;;
  \?)
    echo "Invalid option: -$OPTARG" >&2
    exit 1
    ;;
  esac
done

OUT_DIR="out"

if [ -z "$DIRECTORY" ]; then
  echo "You need to specify the source directory with the -d flag"
fi

if [ ! -d "$DIRECTORY" ]; then
  echo "Directory $DIRECTORY does not exist"
fi

if [ ! -d "$OUT_DIR" ]; then
  mkdir "$OUT_DIR"
fi

if [ ! -d "$OUT_DIR/binaries" ]; then
  mkdir "$OUT_DIR"/binaries
fi

cd "$DIRECTORY" || exit 1
go build -o ../"$OUT_DIR"/binaries/"$PACKAGE_NAME"