#!/bin/bash

while getopts ":d:" opt; do
  case $opt in
  d)
    DIRECTORY=$OPTARG
    ;;
  \?)
    echo "Invalid option: -$OPTARG" >&2
    exit 1
    ;;
  esac
done

if [ ! -d "$DIRECTORY" ]; then
  echo "Directory $DIRECTORY does not exist"
  exit 1
fi

cd "$DIRECTORY" || exit 1
swag fmt
swag init -g main.go
