#!/usr/bin/env bash

while getopts ":d:" opt; do
  case $opt in
  d)
    DIRECTORY=$OPTARG
    ;;
  \?)
    echo "Invalid option: -$OPTARG" >&2
    exit 1
    ;;
  esac
done

if [ -z "$DIRECTORY" ]; then
  echo "You need to specify the source directory with the -d flag"
fi

if [ ! -d "$DIRECTORY" ]; then
  echo "Directory $DIRECTORY does not exist"
fi

cd "$DIRECTORY" || exit 1
go test ./...