replicaCount: 1

image:
  repository: cjlapao/prl-devops-service
  pullPolicy: always
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
namespace: default

serviceAccount:
  create: true
  automount: true
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext:
  {}
  # fsGroup: 2000

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

envFrom:
  []
  # - secretRef:
  #     name: mySecret

storage:
  node_name: ""
  storage_class: "manual"
  storage_size: "1Gi"
  access_mode: "ReadWriteOnce"
  databasePath: "/go/bin/db"
  autoRecover: true

security:
  jwt:
    rsa_private_key: ""
    hmac_secret: ""
    duration: "15m"
    signing_method: "HS256"
  password:
    min_password_length: 12
    max_password_length: 40
    require_uppercase: true
    require_lowercase: true
    require_numbers: true
    require_special_characters: true
    salt_password: true
  brute_force:
    max_login_attempts: 5
    lockout_duration: 10s
    increment_lockout_duration: true
  encryption_private_key: ""
  root_password: ""
  enable_tls: false
  disable_tls_validation: false

service:
  type: ClusterIP
  port: 80
  targetPort: 80

logLevel: info

config:
  mode: "api"
  disableCatalogCaching: false

ingress:
  enabled: false
  istio:
    enabled: false
    gateway: ""
    create_gateway: false
  nginx:
    enabled: false
    ingressClassName: nginx
  prefix: parallels
  annotations: {}
  host: ""
  apiPrefix: /api

  tls:
    enabled: false
    port: 443
    tls_secret_name: ""
    caCertificate:
    certificate:
    privateKey:

resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
